---
title: "About this Project"
---

This project is the result of a meaningful collaboration across The Nature Conservancy, serving as a demonstration of data products that may be created using LANDFIRE data. These charts, maps, and graphs are based on current LANDFIRE products, and provide a starting point for further analysis. All maps, input datasets and further assistance can be obtained by contacting TNC Ecologists (and authors of this assessment), [Randy Swaty](mailto:rswaty@tnc.org){target="blank"} and [Melanie Rudolf](mailto:melanie.rudolf@tnc.org){target="blank"}. 

## What is LANDFIRE?
[LANDFIRE](https://landfire.gov/){target='blank'}, Landscape Fire and Resource Management Planning Tools , is a shared program between the wildland fire management programs of the U.S. Department of Agriculture Forest Service Fire and Aviation branch, and the U.S. Department of the Interior, that provides more than twenty landscape-scale geo-spatial products, 950 vegetation models, and a suite of tools that support all-lands planning, management, and operations.  


## What is The Nature Conservancy’s connection? 
The Nature Conservancy (TNC) is a  Major Partner  in the LANDFIRE Program supported by a cooperative agreement. TNC’s LANDFIRE Team works closely with the LANDFIRE Business Leads, program staff, and other partners to provide user support through:  

* Helping users understand the strengths, weaknesses, and appropriate uses of LANDFIRE products
* Locating, obtaining, and using geospatial data, tools, and models for fire and natural resource management, planning, and implementation
* Identifying and comparing management priorities, evaluating threats to ecosystems, and exploring outcomes under alternative management scenarios

## LANDFIRE's Mission 
LANDFIRE's mission is to provide agency leaders and managers with a common "all-lands" data set of vegetation and wildland fire/fuels information for strategic fire and resource management planning and analysis. 

## Biophysical Settings Products

#### Quick intro

A Biophysical Setting (BpS) is a concept that represents the vegetation that may have been dominant on the landscape prior to European colonization of North America and is based on both the current biophysical environment and an approximation of the historical disturbance regime.

LANDFIRE collaborated with experts around the country to create a description and model for every BpS it mapped across the US.

Check out the vegetation modeling website to learn how to integrate BpS into your work.

#### Resources

-   [Vegetation dynamics models: a comprehensive set for natural resource assessment and planning in the United States](https://esajournals.onlinelibrary.wiley.com/doi/pdf/10.1002/ecs2.3484){target="blank"}. Kori Blankenship, Randy Swaty, Kimberly R. Hall, Sarah Hagen, Kelly Pohl, Ayn Shlisky Hunt, Jeannie Patton, Leonardo Frid, Jim Smith
-   [BpS Descriptions and Models information](https://landfire.gov/bps-models.php){target="blank"}
-   [Information about the BpS Spatial Data](https://landfire.gov/bps.php){target="blank"}
-   Learn to work with the BpS models at our [Vegetation Modeling Website](https://thenatureconservancy.github.io/landfiremodels/){target='blank'}

<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/xjaWJCe7udQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

<br>

## Vegetation Products

#### Quick Intro

LANDFIRE  existing vegetation layers describe the following elements: Existing Vegetation Type, Existing Vegetation Canopy Cover, and Existing Vegetation Height (EVH). These layers are created using predictive landscape models based on extensive field-referenced data, satellite imagery and biophysical gradient layers using classification and regression trees.' (from https://landfire.gov/vegetation.php)

#### Resources

-   [Existing Vegetation Cover](https://landfire.gov/evc.php){target="blank"}
-   [Existing Vegetation Height](https://landfire.gov/evh.php){target="blank"}
-   [Existing Vegetation Type](https://landfire.gov/evt.php){target="blank"} <br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/R3Jn6sxaXR0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>
